# Generated by Django 4.2.11 on 2024-05-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_movies_pics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies_pics',
            name='photo',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
