# Generated by Django 4.2.11 on 2024-05-03 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0010_alter_movies_pics_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies_pics',
            name='photo',
            field=models.ImageField(blank=True, default='elon2.jpg', null=True, upload_to='images/'),
        ),
    ]
