# Generated by Django 4.2.11 on 2024-05-03 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0011_alter_movies_pics_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies_list',
            name='movie_picture',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movie', to='sample.movies_pics'),
        ),
    ]
