# Generated by Django 4.2.11 on 2024-05-03 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0014_alter_movies_list_produced_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(max_length=100)),
                ('actor_age', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director_name', models.CharField(max_length=100)),
                ('director_age', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='movies_list',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='movies_list',
            name='director',
        ),
        migrations.RemoveField(
            model_name='movies_list',
            name='produced_by',
        ),
        migrations.DeleteModel(
            name='Producer',
        ),
        migrations.AddField(
            model_name='movies_list',
            name='directed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produced_man', to='sample.director'),
        ),
    ]
