# Generated by Django 4.2.11 on 2024-05-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0015_actors_director_remove_movies_list_actor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies_list',
            name='actors',
            field=models.ManyToManyField(null=True, related_name='acted_by', to='sample.actors'),
        ),
    ]
