# Generated by Django 4.2.11 on 2024-05-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0016_movies_list_actors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies_list',
            name='actors',
            field=models.ManyToManyField(related_name='acted_by', to='sample.actors'),
        ),
    ]
